; Generated 2026-03-21T17:25:22.126731

almanac/
├─ app/
│  ├─ api/
│  │  └─ chunk/
│  │     └─ route.js
│  ├─ blog/
│  │  ├─ [...slug]/
│  │  │  └─ page.tsx
│  │  ├─ layout.tsx
│  │  └─ page.tsx
│  ├─ test/
│  │  ├─ page.jsx
│  │  └─ pdfviewer.tsx
│  ├─ globals.css
│  ├─ layout.tsx
│  ├─ not-found.tsx
│  └─ page.tsx
├─ components/
│  ├─ BlogShell.jsx
│  ├─ PrintButton.jsx
│  ├─ Sidebar.tsx
│  ├─ ThemeToggle.jsx
│  └─ VirtualNote.jsx
├─ lib/
│  └─ notes.js
├─ notes/
│  ├─ AI and ML/
│  │  ├─ CodeML.html
│  │  └─ ML.html
│  ├─ OS/
│  ├─ ch1_new.pdf
│  ├─ System Protection.pdf
│  └─ Types of Operating Systems.pdf
├─ public/
│  ├─ base-control.css
│  ├─ base.css
│  ├─ dtbom.png
│  ├─ fluent.css
│  ├─ print.css
│  └─ robots.txt
├─ .gitignore
├─ next-env.d.ts
├─ next.config.js
├─ package-lock.json
├─ package.json
├─ postcss.config.js
├─ README.md
├─ tailwind.config.js
├─ tsconfig.json
└─ vercel.json